import { IconType } from 'react-icons'
import {
  SiAndroid as AndroidIcon,
  SiAmazonaws as AwsIcon,
  SiMicrosoftazure as AzureIcon,
  SiCplusplus as CppIcon,
  SiCsharp as CsharpIcon,
  SiCss3 as CssIcon,
  SiDocker as DockerIcon,
  SiDotnet as DotNetIcon,
  SiExpress as ExpressIcon,
  SiGooglecloud as GcpIcon,
  SiHtml5 as HtmlIcon,
  SiJava as JavaIcon,
  SiJavascript as JavaScriptIcon,
  SiJest as JestIcon,
  SiLaravel as LaravelIcon,
  SiMaterialui as MuiIcon,
  SiMysql as MySqlIcon,
  SiNextdotjs as NextJsIcon,
  SiNodedotjs as NodeIcon,
  SiOkta as OktaIcon,
  SiPhp as PhpIcon,
  SiPostgresql as PostgreSqlIcon,
  SiPython as PythonIcon,
  SiReact as ReactIcon,
  SiRedux as ReduxIcon,
  SiSpringboot as SpringBootIcon,
  SiStorybook as StorybookIcon,
  SiTestinglibrary as TestingLibraryIcon,
  SiTypescript as TypeScriptIcon,
  SiUnity as UnityIcon,
} from 'react-icons/si'

const icons: { [key: string]: IconType } = {
  android: AndroidIcon,
  java: JavaIcon,
  python: PythonIcon,
  node: NodeIcon,
  express: ExpressIcon,
  springboot: SpringBootIcon,
  postgresql: PostgreSqlIcon,
  mysql: MySqlIcon,
  js: JavaScriptIcon,
  ts: TypeScriptIcon,
  react: ReactIcon,
  html: HtmlIcon,
  css: CssIcon,
  next: NextJsIcon,
  storybook: StorybookIcon,
  jest: JestIcon,
  testinglibrary: TestingLibraryIcon,
  aws: AwsIcon,
  azure: AzureIcon,
  gcp: GcpIcon,
  cpp: CppIcon,
  docker: DockerIcon,
  php: PhpIcon,
  laravel: LaravelIcon,
  redux: ReduxIcon,
  mui: MuiIcon,
  csharp: CsharpIcon,
  dotnet: DotNetIcon,
  okta: OktaIcon,
  unity: UnityIcon,
}

export default icons
